# Generated by Django 4.0.4 on 2024-03-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname_item', models.CharField(max_length=30)),
                ('tprice', models.FloatField()),
                ('tavailability', models.BooleanField()),
                ('tpicture', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('availability', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('confpassword', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.IntegerField(max_length=11)),
            ],
        ),
    ]
